### PR TITLE
feat: allow querying for unknown fields

### PR DESCRIPTION
**Pull request by angeloashmore**
Adds the ability to query for fields defined in Prismic but without content.

## Use Case

A Page custom types includes a `title` field, but has no value on any instance of Page. Because the field is empty everywhere, Gatsby does not know it exists. Querying for the field in a GraphQL query will cause the query runner to throw an error.

This is especially useful for Prismic since fields cannot be marked as required in Prismic.

## Progress

- [x] Parse Prismic JSON schema into GraphQL schema
  - [x] Color
  - [x] Select
  - [x] Text
  - [x] UID
  - [x] StructuredText
  - [x] Number
  - [x] Date
  - [x] Timestamp
  - [x] GeoPoint
  - [x] Embed
  - [x] Image
  - [x] Link
  - [x] Group
  - [x] Slice
  - [x] Slices
- [x] Create node relationships
  - [x] Group (no relationship, but must be processed recursively)
  - [x] Slice (no relationship, but must be processed recursively)
  - [x] Slices (no relationship, but must be processed recursively)
  - [x] Image
  - [x] Link
- [x] Create and delete temporary nodes
- [x] Refactor
- [x] Document
- [x] Publish to NPM as alpha

### CODE REVIEW

**Comment by angeloashmore** [comment]
File fields should be mocked in `createTemporaryAccessoryMockNodes` by using `createRemoteFileNode`. I assume we need to download an actual image for the sharp transformers to kick in.

**Comment by angeloashmore** [comment]
@simplesessions Do you have experience with embed fields? Is there a standard set of fields returned?

This is what I'm seeing for a Gist:

```js
embed: {
  gist: "angeloashmore/f7a2566b65de04b0810df4c6f92cf382"
  embed_url: https://gist.github.com/angeloashmore/f7a2566b65de04b0810df4c6f92cf382
  type: "rich"
  version: "1.0"
  title: "React Preload Component"
  author_name: null
  author_url: null
  provider_name: "GitHub"
  provider_url: https://gist.github.com
  cache_age: null
  thumbnail_url: https://gist.github.com/fluidicon.png
  thumbnail_width: null
  thumbnail_height: null
  html: "<script src="https://gist.github.com/angeloashmore/f7a2566b65de04b0810df4c6f92cf382.js"></script>"
}
```

**Comment by simplesessions** [comment]
@angeloashmore I've used embed fields for YouTube videos before and that seems to match what Prismic was handing me back for their oEmbed support.

**Comment by angeloashmore** [comment]
@simplesessions Ok thanks, we'll start with that then.

**Comment by angeloashmore** [comment]
Link's `document___NODE` field can be mocked with instances of all custom types. Since the plugin always defaults to an array with one item, this should be compatible.

**NOTE**: Need to be careful about circular deps.

**Comment by angeloashmore** [comment]
Published to NPM as `v2.3.0-alpha.1`

**Comment by gyzerok** [comment]
The feature is amazing, can't wait it being released! Great job 👍

**Comment by like-vyk** [comment]
@angeloashmore are you any closer to alpha 6 release? Would love to get the empty fields issue resolved.

**Comment by angeloashmore** [comment]
@like-vyk Our hope is to release a beta of a new major version by the end of this week including the schema integration and client-side previews.

There are breaking changes in this release that fix several long-standing issues so we'll still need others to test before releasing `v3.0`. We are testing internally with our existing Prismic clients and so far everything is working as expected.

**Comment by angeloashmore** [comment]
Closing in favor of #96

**Pull request closed without merging**
