### PR TITLE
Prismic-Toolbar

### PR DESCRIPTION
**Pull request by MarcMcIntosh**
Hello,
We've added the prismic-tool bar is an opt-in feature that can be enabled in the plugins config by setting `prismicToolbar: true`

This will prevent users experiencing any surprises when use a more recent version of the plugin

### CODE REVIEW

**Comment by angeloashmore** [comment]
Hi @MarcMcIntosh, very busy with work the past week but I can take a closer look at this over the weekend. Looks good at first glance.

**Comment by angeloashmore** [comment]
@MarcMcIntosh Cleaned up some of the code, fixed the tests, and updated documentation.

I can't get the `gatsby-ssr.ts` script to run in a project, however. Are you successfully seeing the toolbar appear?

**Comment by veloce** [comment]
@angeloashmore we've tested the `gatsby-ssr.ts` it was working for us, even though it was difficult to make it work with the build. 
The key here is just to include the script in the header for all pages. so if you have another alternative that may work better we can change that.

**Comment by MarcMcIntosh** [comment]
Hi @angeloashmore,

I can see from the [commit history](https://github.com/MarcMcIntosh/gatsby-source-prismic/commits/toolbar/gatsby-ssr.js) that you've run into the same issue we had with `gatsby-ssr`.

Reverting this change should make it work :)

**Comment by MarcMcIntosh** [comment]
@angeloashmore it works now :)
here's a sample project :)

**Comment by angeloashmore** [comment]
Ah, thanks for pointing that out. I should have time to take a look at this again tomorrow (Friday) or over the weekend.

On the subject of improving previews, here's an in-depth RFC on how we can make previews easier for developers: https://github.com/angeloashmore/gatsby-source-prismic/issues/223

Would love to get your thoughts!

**Pull request merged**
