### PR TITLE
Add shouldNormalizeImage option for v1

### PR DESCRIPTION
**Pull request by simplesessions**
Enable shouldNormalizeImage for v1.

### CODE REVIEW

**Comment by angeloashmore** [comment]
LGTM! I'll publish under the `gatsby-v1` tag.

**Comment by angeloashmore** [comment]
Published as `v1.3.0`!

It can be installed via `npm install gatsby-source-prismic@gatsby-v1`. We should probably update the master README with instructions for Gatsby v1 users.

**Comment by simplesessions** [comment]
Thanks for the quick merge! I can throw up a README update sometime soon if you haven't already worked on it.

**Comment by angeloashmore** [comment]
That would be awesome 👍

**Pull request merged**
