### PR TITLE
[WIP] feat: support multiple repositories

### PR DESCRIPTION
**Pull request by heart-of-code**
@angeloashmore This still needs some work. 

Things that do seem to be working fine:

- [x] applying the prefix to all the Prismic types
- [x] updated unit tests 
- [x] updated some of the tests to work with Windows file paths except one (replacing it with regex didn't seem to be accepted by the function)

I'm unfamiliar with typescript so I ran into some issues. Here's a list of things that need to be checked or fixed:

- [x] "typenamePrefix" is currently not optional because I wasn't able to get a default value to cooperate with the typescript interface. This would make it a breaking change, which I imagine is undesirable.
- [x] Unable to run `gatsby develop` successfully due to the following error and am unsure how to debug this error from the details provided:
```
Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value: PrismicMyPrefixImageFixedType.'. Stacktrace was 'Error: Cannot 
create as TypeComposer the following value: PrismicMyPrefixImageFixedType.
    at SchemaComposer.createTempTC (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\graphql-compose\lib\SchemaComposer.js:365:11)
    at SchemaComposer.addAsComposer (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\graphql-compose\lib\SchemaComposer.js:563:27)
    at processAddedType (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\schema.js:396:35)
    at forEach (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\schema.js:321:9)
    at Array.forEach (<anonymous>)
    at addTypes (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\schema.js:247:9)
    at updateSchemaComposer (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\schema.js:134:9)
    at buildSchema (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\schema.js:61:9)
    at build (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\index.js:105:24)
    at buildSchema (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\services\build-schema.ts:19:3)'
```

### CODE REVIEW

**Comment by angeloashmore** [comment]
@heart-of-code I added some commits based on your work.

- Made `typenamePrefix` optional.
- Fixed the `gatsby develop` error. Non-schema-specific types, such as images, will not need to use the prefix.
- Cleaned up some of the tests (we shouldn't need to test for `typenamePrefix` explicitly in `usePrismicPreview` since it pulls that in directly from the typePaths JSON file).
- Updated the README.

Everything seems to work fine, but are you able to test on your end with an actual Gatsby site?

**Comment by heart-of-code** [comment]
Thank you !! I'll pull this down and test it locally

**Comment by heart-of-code** [comment]
I'm still experiencing issues with TypeComposer, but I think it might be because when I try to use npm link I end up with duplicate instances of Gatsby? I'm trying to figure it out 😅

**Comment by angeloashmore** [comment]
I'm using Yarn, but you should be able to accomplish the same thing with NPM, albeit with probably a different set of commands:

```
cd <path>/gatsby-source-prismic
yarn link

cd <path>/test-gatsby-site
yarn link gatsby-source-prismic
cd node_modules/gatsby
yarn link
cd ../react
yarn link

cd <path>/gatsby-source-prismic
yarn link gatsby react
```

Basically, this will link gatsby-source-prismic, gatsby, and react between both directories. This could also be accomplished automatically with a Yarn workspace.

**Comment by angeloashmore** [comment]
@heart-of-code LMK if it's still not working and I can publish a pre-release version to test.

**Comment by heart-of-code** [comment]
@angeloashmore I uninstalled my modules, switched over to using yarn, and followed your steps. Good news: the prefixing worked with a single gatsby-source-prismic plugin. Bad news: when I added a second one (first tried as a duplicate with a new prefix, second with a different prismic repo) I got another error that seems unrelated to your actual code:
```
Missing onError handler for invocation 'building-schema', error was 'TypeError: defineFieldMapToConfig is not a function'. Stacktrace was 'TypeError: defineFieldMapToConfig is not a function
    at mergeTypes (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\schema.js:356:17)
    at forEach (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\schema.js:312:9)
    at Array.forEach (<anonymous>)
    at addTypes (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\schema.js:247:9)
    at updateSchemaComposer (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\schema.js:134:9)
    at buildSchema (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\schema.js:61:9)
    at build (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\schema\index.js:105:24)
    at buildSchema (C:\Users\Aveline\Documents\Corvids Emporium\corvidsemporium.com\node_modules\gatsby\src\services\build-schema.ts:19:3)'
```

**Comment by angeloashmore** [comment]
I think the issue was related to the image types being shared. I was wrong - images *do* need to be namespaced since they could have different Imgix URL parameters.

I pushed up a fairly large set of commits that converts `gqlTypes.ts` to create the base types in code rather than in a string (i.e. SDL). This allows us to more easily namespace types using the `buildSchemaTypeName` helper.

This change presents a new problem: the image fragments (e.g. `GatsbyPrismicImageFluid`) now spreads on a non-existent type if a namespace is present.

The following example is using `typenamePrefix: 'First'`:

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "PrismicImageFluidType". Did you mean "PrismicFirstImageFluidType", "PrismicSecondImageFluidType", "PrismicEmbedType", "PrismicImageThumbnailType", or "PrismicFirstImageFixedType"?

GraphQL request:2:39
1 |
2 |   fragment GatsbyPrismicImageFluid on PrismicImageFluidType {
  |                                       ^
3 |     base64

File: src/templates/page.tsx:118:39
```

So the fragments need to be made programmatically. Gatsby picks these fragments up by reading the files and looking for `graphql`, so there isn't an easy to way just call a function and make them available, as far as I know. I'm kind of stumped here.

**Comment by angeloashmore** [comment]
Note that `node_modules/gatsby/index.d.ts` needs to be manually patched locally until this PR is merged: https://github.com/gatsbyjs/gatsby/pull/26032

You will see an error when running `yarn build` without those changes.

**Comment by heart-of-code** [comment]
Thanks, I'll take a look tomorrow and see if I can come up with any ideas to get through this!

**Comment by angeloashmore** [comment]
I think the solution is to change the fragments to use a GraphQL interface rather than a type (i.e. create and implement an interface on the image types). Sorry, this is taking longer than I figured it would but I'll try to spend more time on this as well.

**Comment by heart-of-code** [comment]
> Sorry, this is taking longer than I figured it 
Estimates before digging into the work are rarely accurate, it's totally okay 😄

**Comment by angeloashmore** [comment]
Closing this PR as this functionality has been integrated into the next major version of the plugin currently in development.

**Comment by heart-of-code** [comment]
> Closing this PR as this functionality has been integrated into the next major version of the plugin currently in development.

🎉🎉🎉🎉 can't wait!

**Comment by angeloashmore** [comment]
@heart-of-code It's out now! It can be configured using the `typePrefix` option in `gatsby-source-prismic`.

See `options.typePrefix`: https://prismic.io/docs/technologies/install-the-plugin-gatsby#3.-configure-the-plugin

Thanks for your work in this PR. It set the foundation for supporting multiple repositories in a Gatsby project. 🙂

**Pull request closed without merging**
