### PR TITLE
createNodeId usage

### PR DESCRIPTION
**Pull request by MarcMcIntosh**
Addresses #297 
craeteNodeId should be called with the document id only as when a document is removed only the document id will be known

### CODE REVIEW

**Comment by MarcMcIntosh** [comment]
I'll tests this out in a project tomorrow :)

**Comment by MarcMcIntosh** [comment]
Also @angeloashmore does this project use any CI to run tests automatically?

**Comment by angeloashmore** [comment]
@MarcMcIntosh Thanks for the updates here 👍

No, there isn't CI setup on the project to run tests automatically but it's something that should be added. The `yarn test` script is setup to run just locally for now.

I've been using this simple GitHub Actions workflow on other libraries: https://github.com/angeloashmore/gatsby-plugin-local-search/blob/d11a766a3278f7961e43b83e923d63617da4c956/.github/workflows/main.yml

Feel free to recommend something different or even another PR to add CI.

**Comment by MarcMcIntosh** [comment]
Hi @angeloashmore I tested the changes in a sample project and things still work :)

I'll add looking into actions for a CI option normally I use travis, but it maybe better :D

**Comment by angeloashmore** [comment]
@MarcMcIntosh Awesome, looks good to me 👍.

I made one small change to support link fields without a document ID (https://github.com/angeloashmore/gatsby-source-prismic/pull/310/commits/9fb0ded00bbec35bd403596f537c8a0120467fd3).

I've tested it on a real website and everything works as expected so I'll publish the new version.

**Review by angeloashmore — APPROVED** [review]

**Pull request merged**
